<a href="https://colab.research.google.com/github/kurangjauh/DataMining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [5]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Italy' 25.0 72000.0]
 ['Uruguay' 27.0 48000.0]
 ['Palestine' 30.0 54000.0]
 ['Baghdad' 29.0 61000.0]
 ['Baghdad' 22.0 nan]
 ['Uruguay' 25.0 58000.0]
 ['Italy' nan 52000.0]
 ['Palestine' 28.0 79000.0]
 ['Uruguay' 20.0 83000.0]
 ['Italy' 27.0 67000.0]]


In [6]:
print(y)

['Yes' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes']


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [9]:
print(x)

[['Italy' 25.0 72000.0]
 ['Uruguay' 27.0 48000.0]
 ['Palestine' 30.0 54000.0]
 ['Baghdad' 29.0 61000.0]
 ['Baghdad' 22.0 63777.77777777778]
 ['Uruguay' 25.0 58000.0]
 ['Italy' 25.88888888888889 52000.0]
 ['Palestine' 28.0 79000.0]
 ['Uruguay' 20.0 83000.0]
 ['Italy' 27.0 67000.0]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0.0 1.0 0.0 0.0 25.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 29.0 61000.0]
 [1.0 0.0 0.0 0.0 22.0 63777.77777777778]
 [0.0 0.0 0.0 1.0 25.0 58000.0]
 [0.0 1.0 0.0 0.0 25.88888888888889 52000.0]
 [0.0 0.0 1.0 0.0 28.0 79000.0]
 [0.0 0.0 0.0 1.0 20.0 83000.0]
 [0.0 1.0 0.0 0.0 27.0 67000.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[1 1 0 0 0 1 0 0 1 1]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [18]:
print(x_train)

[[0.0 1.0 0.0 0.0 25.88888888888889 52000.0]
 [1.0 0.0 0.0 0.0 22.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 25.0 72000.0]
 [1.0 0.0 0.0 0.0 29.0 61000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 28.0 79000.0]
 [0.0 0.0 0.0 1.0 20.0 83000.0]
 [0.0 0.0 0.0 1.0 25.0 58000.0]]


In [19]:
print(x_test)

[[0.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 27.0 67000.0]]


In [20]:
print(y_train)

[0 0 1 0 1 0 1 1]


In [21]:
print(y_test)

[0 1]


In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [25]:
print(x_train)

[[0.0 1.0 0.0 -0.7745966692414833 0.23198352712899736 -1.0781259408412427]
 [1.0 0.0 0.0 -0.7745966692414833 -1.1500459961926883
  -0.07013167641635404]
 [0.0 1.0 0.0 -0.7745966692414833 -0.0839089353445309 0.6335624327104546]
 [1.0 0.0 0.0 -0.7745966692414833 1.3376071457863454 -0.307866172742979]
 [0.0 0.0 0.0 1.2909944487358056 0.6268491052209074 -1.4204636155515822]
 [0.0 0.0 1.0 -0.7745966692414833 0.9822281255036265 1.2326533634535488]
 [0.0 0.0 0.0 1.2909944487358056 -1.8608040367581267 1.5749910381638883]
 [0.0 0.0 0.0 1.2909944487358056 -0.0839089353445309 -0.5646194287757336]]


In [26]:
print(x_test)

[[0.0 0.0 1.0 -0.7745966692414833 1.6929861660690646 -0.9069571034860731]
 [0.0 1.0 0.0 -0.7745966692414833 0.6268491052209074 0.20564033932253026]]
